// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
  }
}

type Pages = {
  "/": {
    params: Record<string, never>;
  };
  "/oauth_success": {
    params: Record<string, never>;
  };
  "/about": {
    params: Record<string, never>;
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/explore": {
    params: Record<string, never>;
  };
  "/book": {
    params: Record<string, never>;
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/oauth_success" | "/about" | "/*" | "/explore" | "/book";
  };
  "pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "pages/OauthSuccess.tsx": {
    id: "pages/OauthSuccess";
    page: "/oauth_success";
  };
  "pages/AboutUs.tsx": {
    id: "pages/AboutUs";
    page: "/about";
  };
  "pages/NotFound.tsx": {
    id: "pages/NotFound";
    page: "/*";
  };
  "pages/exploreMain.tsx": {
    id: "pages/exploreMain";
    page: "/explore";
  };
  "pages/Booking.tsx": {
    id: "pages/Booking";
    page: "/book";
  };
};
